Feature/header nav search
aquilasfr/site-IPJA pull request #1
Opened 2021-06-23 19:37 UTC by aquilasfr

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +    --color-segundary: #99d0b5;
corrgir nome da variável para `--color-secundary`

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +    --color-top-footer: #454545;
o ideal é que as variáveis tenham nomes que não estejam atrelados a elementos.

**Sugestão:** Vejo que a primary é uma versão mais escura que a secondary, recomendo que use da seguinte forma:

```scss
--color-primary-main: #429b6e;
--color-primary-light: #99d0b5;
--color-secondary: #454545;
```

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +    --anchor: whitesmoke;
uma boa prática é utilizar hex colors ao invés do nome. ficando:

```scss
--color-anchor: #f5f5f5;
```

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +    background-color: var(--color-top-footer);
Aqui esta um exemplo de variável atrelada a um elemento, você esta usando um variável chamada `footer` no `header`, com a alteração do comentário anterior ficará:

```scss
.header {
    background-color: var(--color-secondary);
}
```

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +        height: 79px;
Esse `height: 79px` é necessário? é 1px a menos que o elemento pai, poderia ser removido, não?

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +                width: 80%;
Recomendo que você utilize a largura em pixels no logo para não acabar distorcendo.

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +                        font-family: Arial, Helvetica, sans-serif;
recomendo que você mova o `font-family` para a tag `body`, assim não será necessário repetir em vários lugares.

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +                    padding: 15px 270px 15px 20px;
Qual o motivo para utilizar o padding de 270px? Parece ser um número mágico :thinking:

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +                    font-size: 20px;
Recomendo armazenar esse valor em uma variável, já que é utilizado em mais de um lugar.

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +                    background-color: #99d0b5;
Utilizar a variável existente com esse valor.

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +                    background-color: #99d0b5;
Utilizar a variável existente com esse valor.

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +                    font-size: 20px;
utilizar a variável que padroniza o tamanho das fontes, conforme dito no comentário anterior.

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +                    color: white;
utilizar hexadecimal no lugar do nome

2021-06-23 20:10 UTC, rafaelnai commented on assets/style.scss
> +                        color:snow;
o mesmo aqui

2021-06-23 20:10 UTC, rafaelnai commented on index.html
> +        </div>
Pelo que vi no layout, o `header` deveria fechar nesse ponto, tornando o seu html mais simples, algo como:

 ```html
<header class="header">
  <ul class="header__social-medias">
    <li>
      <a class="header__social-medias__anchor" href=""><i class="fab fa-instagram"></i></a>
    </li>
    <li>
      <a class="header__social-medias__anchor" href=""><i class="fab fa-facebook-square"></i></a>
    </li>
    <li>
      <a class="header__social-medias__anchor" href=""><i class="far fa-envelope"></i></a>
    </li>
    <li>
      <a class="header__social-medias__anchor" href=""><i class="fab fa-youtube"></i></a>
    </li>
  </ul>
  <a class="header__contact" href=""><i class="fas fa-phone-alt"></i>(00)0000-0000</a>
</header>
```

2021-06-23 20:10 UTC, rafaelnai commented on index.html
> +        <div class="header__wrapper-content">
Aqui você pode iniciar uma nova seção fora do header.

2021-06-23 20:10 UTC, rafaelnai commented on index.html
> +            <div class="header__wrapper-content__nav">
substituir a tag `div` por `nav`

2021-06-24 01:20 UTC, aquilasfr commented on assets/style.scss
> +    --color-segundary: #99d0b5;
Feito

2021-06-24 01:28 UTC, aquilasfr commented on assets/style.scss
> +    --color-top-footer: #454545;
Feito

2021-06-24 01:29 UTC, aquilasfr commented on assets/style.scss
> +    --anchor: whitesmoke;
Feito

2021-06-24 01:30 UTC, aquilasfr commented on assets/style.scss
> +    background-color: var(--color-top-footer);
Feito

2021-06-24 01:35 UTC, aquilasfr commented on assets/style.scss
> +        height: 79px;
Tirei o height de 80px do header e deixei no wrapper.

2021-06-24 01:38 UTC, aquilasfr commented on assets/style.scss
> +                width: 80%;
Coloquei uma largura de 500px

2021-06-24 01:42 UTC, aquilasfr commented on assets/style.scss
> +                        font-family: Arial, Helvetica, sans-serif;
Feito

2021-06-24 01:47 UTC, aquilasfr commented on assets/style.scss
> +                    padding: 15px 270px 15px 20px;
Não consegui fazer, e sim sabia que você ia falar rs

2021-06-24 01:48 UTC, aquilasfr commented on assets/style.scss
> +                    font-size: 20px;
feito.

2021-06-24 01:48 UTC, aquilasfr commented on assets/style.scss
> +                    background-color: #99d0b5;
Feito.

2021-06-24 01:48 UTC, aquilasfr commented on assets/style.scss
> +                    background-color: #99d0b5;
Feito.

2021-06-24 01:49 UTC, aquilasfr commented on assets/style.scss
> +                    font-size: 20px;
Feito.

2021-06-24 01:52 UTC, aquilasfr commented on assets/style.scss
> +                    color: white;
Feito.

2021-06-24 01:53 UTC, aquilasfr commented on assets/style.scss
> +                        color:snow;
Feito.

2021-06-24 17:21 UTC, aquilasfr commented on index.html
> +        </div>
feito

2021-06-24 18:14 UTC, aquilasfr commented on index.html
> +        <div class="header__wrapper-content">
feito

2021-06-24 18:14 UTC, aquilasfr commented on index.html
> +            <div class="header__wrapper-content__nav">
feiuto

2021-06-24 18:54 UTC, rafaelnai commented on assets/style.scss
> +    --color-secundary: #454545;
secondary*

2021-06-24 18:54 UTC, rafaelnai commented on assets/style.scss
> +    --border-nav: 20px;
Não atrelar nome de variáveis a elementos

2021-06-24 18:54 UTC, rafaelnai commented on index.html
> +                <ul>
Remover `ul` e adicionar na lista de social-medias na última posição.

2021-06-24 18:54 UTC, rafaelnai commented on assets/style.scss
> +    &__social-medias {
Para justificar os contatos a direita, você pode pegar o último item da lista dessa forma:

```scss
&__social-medias {
  li:last-child {
    flex-grow: 1;
    text-align: right;
  }
}
```

2021-06-24 18:54 UTC, rafaelnai commented on assets/style.scss
> +        width: 500px;
Para não quebrar o layout no celular:

```scss 
{
  width: 100%;
  max-width: 500px
}
```

2021-06-24 18:54 UTC, rafaelnai commented on assets/style.scss
> +                padding: 15px 270px 15px 20px;
Remover o número mágico e utilizar flex-box para ajustar os elementos na tela

2021-06-25 13:35 UTC, aquilasfr reviewed
removido número mágico e adicionado:
                padding-left: 16px;
                width: 70%;
                height: 45px;

2021-06-25 13:35 UTC, aquilasfr commented on assets/style.scss
> +    --color-secundary: #454545;
Feito.

2021-06-25 13:35 UTC, aquilasfr commented on assets/style.scss
> +        width: 500px;
feito

2021-06-25 13:36 UTC, aquilasfr commented on assets/style.scss
> +                padding: 15px 270px 15px 20px;
removido número mágico e adicionado:
padding-left: 16px;
width: 70%;
height: 45px;

2021-06-25 13:37 UTC, aquilasfr commented on assets/style.scss
> +    &__social-medias {
Não consegui aplicar esse código, provavelmente estou fazendo errado.
Segue como está o meu código:

.header {
    width: 100%;
    background-color: var(--color-secondary);
    height: 60px;
    display: flex;
    align-items: center;
    &__social-medias {
        display: flex;
        font-size: var(--icon-lg);
        &__item {
            &__anchor {
                color: var(--anchor);
                margin: 8px;
                text-decoration: none;
                font-size: var(--icon-lg);
            }
        }
    }
}

2021-06-28 13:25 UTC, rafaelnai commented on assets/style.scss
> +    &__social-medias {
Então você pode adicionar o modificador da metodologia `BEM` no último item da lista. Ficando algo como: `header__social-medias__anchor--spaced` e aplicar os estilos

2021-06-28 13:28 UTC, rafaelnai commented on assets/style.scss
> +    --icon-lg: 30px;
não seria melhor font-lg? Pois na maioria dos lugares que usam essa var estão modificando o tamanho da fonte.

2021-06-28 13:38 UTC, rafaelnai commented on assets/style.scss
> +                height: 45px;
Acredito que o padding seja melhor do que o height no caso de campos, pois você quer aumentar o campo e manter o texto centralizado.

2021-06-28 13:53 UTC, aquilasfr commented on assets/style.scss
> +    --icon-lg: 30px;
feitooo

2021-06-28 13:57 UTC, aquilasfr commented on assets/style.scss
> +                height: 45px;
feito padding de 20px

2021-06-28 14:08 UTC, aquilasfr commented on index.html
> +                <ul>
feito

2021-06-28 14:08 UTC, aquilasfr commented on assets/style.scss
> +    --border-nav: 20px;
feito

2021-06-28 17:23 UTC, aquilasfr commented on assets/style.scss
> +                padding: 15px 270px 15px 20px;
removido o height e adiconado um padding.

2021-06-28 17:38 UTC, rafaelnai requested changes

2021-06-28 17:38 UTC, rafaelnai commented on assets/style.scss
> +            &--input {
`--input` não parecer ser um modificador e sim um elemento, correto?

2021-06-28 17:38 UTC, rafaelnai commented on assets/style.scss
> +            &--button {
`--button` não parecer ser um modificador e sim um elemento, correto?

2021-06-28 17:38 UTC, rafaelnai commented on assets/style.scss
> +                font-size: var(--border-nav);
:thinking:

2021-06-28 17:38 UTC, rafaelnai commented on assets/style.scss
> +                font-size: var(--border-nav);
:thinking:

2021-06-28 17:38 UTC, rafaelnai commented on assets/style.scss
> +                    color:#FFFAFA;
Esse link tem a cor diferente dos outros?

2021-06-28 17:38 UTC, rafaelnai commented on index.html
> +                            <i class="fab fa-youtube"></i></a>
Identar essa linha igual as anteriores

2021-06-28 17:38 UTC, rafaelnai commented on index.html
> +                            <i class="fas fa-phone-alt"></i>(00)0000-0000</a>
Aqui também

2021-06-28 17:38 UTC, rafaelnai commented on index.html
> +                        <a class="section-wrapper__nav__list__item--anchor" href="">Início</a>
`--anchor`? :thinking:

2021-06-28 17:38 UTC, rafaelnai commented on index.html
> +                    <button class="section-wrapper__nav__search--button">
`--button`? :thinking:

2021-06-28 17:38 UTC, rafaelnai commented on index.html
> +                    <input class="section-wrapper__nav__search--input" type="text" name="" id="" placeholder="Pesquisar...">
`--input`? :thinking:

2021-06-28 17:38 UTC, rafaelnai commented on index.html
> +                    <button class="section-wrapper__nav__search--button">
Você não precisa desse button, seu `a` pode substitui-lo adicionando a propriedade `appearance: button;` nele.

2021-06-28 17:51 UTC, aquilasfr commented on assets/style.scss
> +            &--input {
feito

2021-06-28 17:51 UTC, aquilasfr commented on assets/style.scss
> +            &--button {
feito

2021-06-28 18:01 UTC, aquilasfr commented on assets/style.scss
> +                font-size: var(--border-nav);
feitooo :+1:

2021-06-28 18:01 UTC, aquilasfr commented on assets/style.scss
> +                font-size: var(--border-nav);
feitoo

2021-06-28 18:04 UTC, aquilasfr commented on assets/style.scss
> +                    color:#FFFAFA;
feitoo...

2021-06-28 18:04 UTC, aquilasfr commented on assets/style.scss
> +                    color:#FFFAFA;
nopss, seria a mesma cor

2021-06-28 18:22 UTC, aquilasfr commented on index.html
> +                            <i class="fab fa-youtube"></i></a>
feitooooo.

2021-06-28 18:22 UTC, aquilasfr commented on index.html
> +                            <i class="fas fa-phone-alt"></i>(00)0000-0000</a>
feito, até mudou o style do contact, estava fora da tag i

2021-06-28 18:33 UTC, aquilasfr commented on index.html
> +                    <input class="section-wrapper__nav__search--input" type="text" name="" id="" placeholder="Pesquisar...">
feito

2021-06-28 19:51 UTC, aquilasfr commented on index.html
> +                        <a class="section-wrapper__nav__list__item--anchor" href="">Início</a>
feito

2021-06-30 01:05 UTC, aquilasfr commented on index.html
> +                    <button class="section-wrapper__nav__search--button">
Não usei o apperance, mas tirei a tag button, somente tirei e coloquei os estilos direto na class anchor.

2021-07-01 19:30 UTC, rafaelnai approved these changes

2021-07-05 17:33 UTC, merged